export const IS_LOADING = 'IS_LOADING';
export const FINISHED_LOADING = 'FINISHED_LOADING';

export const RESET_STATE = 'RESET_STATE';

export const CATEGORIES_DRINKS_FILTER = 'CATEGORIES_DRINKS_FILTER';
export const CATEGORIES_FOODS_FILTER = 'CATEGORIES_FOODS_FILTER';

export const CATEGORIES_FOODS = 'CATEGORIES_FOODS';
export const CATEGORIES_DRINKS = 'CATEGORIES_DRINKS';

export const MAIN_DRINKS = 'MAIN_DRINKS';
export const MAIN_FOODS = 'MAIN_FOODS';

export const FILTERED_DRINKS = 'FILTERED_DRINKS';
export const FILTERED_FOODS = 'FILTERED_FOODS';
